version: 2

jobs:
  release:
    working_directory: ~/googleapis/google-cloud-ruby
    shell: /bin/bash --login -eo pipefail
    docker:
    - image: circleci/ruby:2.5.1-stretch
    steps:
    - checkout
    - run:
        name: Install bundle
        command: gem update --system && gem install bundler --version 1.17.3 && bundle update
    - run: bundle exec rake circleci:release

workflows:
  version: 2
  gem-release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\S+\/v\S+/

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=VdG8EataF3PrWBZOBH7Hr80BXUjYRLh7o
