AllCops:
  Exclude:
    - "acceptance/**/*"
    - "google-cloud-storage.gemspec"
    - "Rakefile"
    - "test/**/*"
    - "support/**/*"
  TargetRubyVersion: 2.2

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/RescueModifier:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 30
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Max: 25
Metrics/ParameterLists:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLines: # for the extra line between copyright and code
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/google-cloud-storage.rb"
Style/RescueStandardError:
  Exclude:
  - "lib/google/cloud/storage/policy.rb"
