AllCops:
  Exclude:
    - "acceptance/**/*"
    - "google-cloud-pubsub.gemspec"
    - "lib/google/pubsub/**/*"
    - "lib/google/cloud/pubsub/v1.rb"
    - "lib/google/cloud/pubsub/v1/**/*"
    - "lib/google/iam/**/*"
    - "Rakefile"
    - "support/**/*"
    - "test/**/*"
  TargetRubyVersion: 2.2

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NumericLiterals:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 25
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Max: 25
  Exclude:
    - "lib/google/cloud/pubsub.rb"
Metrics/ParameterLists:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLines: # for the extra line between copyright and code
  Enabled: false
Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Naming/FileName:
  Exclude:
    - "lib/google-cloud-pubsub.rb"
