AllCops:
  Exclude:
    - "acceptance/**/*"
    - "integration/**/*"
    - "google-cloud-debugger.gemspec"
    - "lib/google/devtools/**/*"
    # GAPIC client has too many violations. Exclude for now.
    - "lib/google/cloud/debugger/v2/**/*"
    - "lib/google/cloud/debugger/v2.rb"
    - "Rakefile"
    - "support/**/*"
    - "test/**/*"
    - "tmp/**/*"
  TargetRubyVersion: 2.2

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NumericLiterals:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Exclude:
    - "lib/google-cloud-debugger.rb"
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Max: 25
Metrics/ParameterLists:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLines: # for the extra line between copyright and code
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/google-cloud-debugger.rb"
Lint/UnifiedInteger:
  Exclude:
    - "lib/google/cloud/debugger/breakpoint/evaluator.rb"
Lint/InheritException:
  Exclude:
    - "lib/google/cloud/debugger/breakpoint/evaluator.rb"
